export type PatientStatus =
  | "CHEGADA_TOTEM"
  | "AGUARDANDO_TRIAGEM"
  | "EM_TRIAGEM"
  | "AGUARDANDO_RECEPCAO"
  | "AGUARDANDO_MEDICO"
  | "EM_ATENDIMENTO"
  | "EM_EXAME"
  | "EM_MEDICACAO"
  | "EM_EXAME_MEDICACAO"
  | "AGUARDANDO_RETORNO_MEDICO"
  | "ALTA"
  | "INTERNACAO"
  | "SAIDA_ANTECIPADA";
